### ISSUE TITLE
Workflow Error!

### ISSUE THREAD

**Issue by albago** [ntmcminn/CounterSign#1]
When you get a workflow to sign a document and click on reject, user that start and review workflow get a 500 error... It happens only if a user reject workflow.

![alfresco editar tarea - google chrome_004](https://f.cloud.github.com/assets/6180549/1744930/1dc36c0c-6426-11e3-8410-c5a3b4020a3c.png)

Suggestion, if its possible to select more than one singer in the workflow...

Thanks!

**Comment by amet123** [comment]
java.lang.NullPointerException: null 
during workflow start another user try to sign alfresco  5.1
